import React from 'react';
import type { Cabinet } from './types';
import type { LucideIcon } from 'lucide-react';
import { Box, Archive, Container, Pentagon, Microwave } from 'lucide-react';

const VanitoryPatasIcon: LucideIcon = (props) => {
  return React.createElement('svg', {
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      ...props
    },
    React.createElement('rect', { x: "3", y: "3", width: "18", height: "18", rx: "1" }),
    React.createElement('rect', { x: "4", y: "4", width: "16", height: "6", rx: "0.5" }),
    React.createElement('path', { d: "M4 10.5h16" }),
    React.createElement('path', { d: "M12 10.5v9.5" })
  );
};

const Vanitory3DrawersIcon: LucideIcon = (props) => {
    return React.createElement('svg', {
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      ...props
    },
      React.createElement('rect', { x: "3", y: "3", width: "18", height: "18", rx: "1" }),
      React.createElement('path', { d: "M4 8.5h16" }),
      React.createElement('path', { d: "M4 14.5h16" })
    );
};

const VanitoryHangingIcon: LucideIcon = (props) => {
  return React.createElement('svg', {
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      ...props
    },
    React.createElement('rect', { x: "3", y: "3", width: "18", height: "18", rx: "1" }),
    React.createElement('rect', { x: "4", y: "13", width: "16", height: "7", rx: "0.5" }),
    React.createElement('path', { d: "M4 12.5h16" })
  );
};


const MELAMINE_THICKNESS = 18;
const MELAMINE_MATERIAL = 'Melamina 18mm';
const BACK_PANEL_MATERIAL = 'MDF 3mm';

// Define cabinets for each category
const bajoMesadaCabinets: Cabinet[] = [
  {
    id: 'base-600',
    name: 'Base 600mm',
    type: 'base',
    icon: Box,
    width: 600,
    height: 720,
    depth: 580,
    pieces: [
      { name: 'Puerta', width: 596, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'base-450',
    name: 'Base 450mm',
    type: 'base',
    icon: Box,
    width: 450,
    height: 720,
    depth: 580,
    pieces: [
      { name: 'Puerta', width: 446, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'base-corner-900',
    name: 'Esquinero Asimétrico',
    type: 'base',
    icon: Pentagon,
    width: 770,
    height: 800,
    depth: 600,
    depth2: 300,
    pieces: [],
  },
];

const alacenaCabinets: Cabinet[] = [
  {
    id: 'wall-600',
    name: 'Alacena 600mm',
    type: 'wall',
    icon: Archive,
    width: 600,
    height: 600,
    depth: 320,
    pieces: [
      { name: 'Puerta', width: 596, height: 596, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'wall-microwave-600',
    name: 'Porta Microondas',
    type: 'wall',
    icon: Microwave,
    width: 600,
    height: 800,
    depth: 400,
    pieces: [],
    defaultComponents: [
      { type: 'opening', height: 400 },
      { type: 'door', height: 400, hinge: 'top' },
    ]
  },
];

const columnaCabinets: Cabinet[] = [
  {
    id: 'tall-600',
    name: 'Columna 600mm',
    type: 'tall',
    icon: Container,
    width: 600,
    height: 2000,
    depth: 580,
    pieces: [
      { name: 'Puerta Superior', width: 596, height: 1246, quantity: 1, material: MELAMINE_MATERIAL },
      { name: 'Puerta Inferior', width: 596, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
];

const vanitoryCabinets: Cabinet[] = [
    {
      id: 'vanity-600-hanging-shelf',
      name: 'Vanitory Colgante 600mm',
      type: 'base', // 'base' so it gets a countertop in 3D view
      icon: VanitoryHangingIcon,
      width: 600,
      height: 500, // e.g., 200 drawer + 300 opening
      depth: 460,
      pieces: [], // Will be generated by logic
      defaultComponents: [
        { type: 'opening', height: 300 },
        { type: 'drawer', height: 200 },
      ]
    },
    {
      id: 'vanity-600-patas',
      name: 'Vanitory 600mm Patas',
      type: 'base',
      icon: VanitoryPatasIcon,
      width: 600,
      height: 840,
      depth: 460,
      pieces: [], // Will be generated by logic
      defaultComponents: [
        { type: 'door', height: 540 },
        { type: 'drawer', height: 200 },
      ]
    },
    {
      id: 'vanity-600-3-drawers',
      name: 'Vanitory 600mm 3 Cajones',
      type: 'base',
      icon: Vanitory3DrawersIcon,
      width: 600,
      height: 840,
      depth: 460,
      pieces: [], // Will be generated by logic
      defaultComponents: [
        { type: 'drawer', height: 246 },
        { type: 'drawer', height: 246 },
        { type: 'drawer', height: 246 },
      ]
    },
];

export const cabinetCategories = [
    { name: "Bajo Mesada", cabinets: bajoMesadaCabinets },
    { name: "Alacenas", cabinets: alacenaCabinets },
    { name: "Columnas", cabinets: columnaCabinets },
    { name: "Vanitory", cabinets: vanitoryCabinets },
];

// Flattened list for compatibility with other parts of the app
export const cabinetData: Cabinet[] = cabinetCategories.flatMap(category => category.cabinets);
