import type { Cabinet } from './types';
import { Box, Archive, Container, Pentagon, Microwave } from 'lucide-react';

const MELAMINE_THICKNESS = 18;
const MELAMINE_MATERIAL = 'Melamina 18mm';
const BACK_PANEL_MATERIAL = 'MDF 3mm';

// Define cabinets for each category
const bajoMesadaCabinets: Cabinet[] = [
  {
    id: 'base-600',
    name: 'Base 600mm',
    type: 'base',
    icon: Box,
    width: 600,
    height: 720,
    depth: 580,
    pieces: [
      { name: 'Puerta', width: 596, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'base-450',
    name: 'Base 450mm',
    type: 'base',
    icon: Box,
    width: 450,
    height: 720,
    depth: 580,
    pieces: [
      { name: 'Puerta', width: 446, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'base-corner-900',
    name: 'Esquinero 770mm',
    type: 'base',
    icon: Pentagon,
    width: 770,
    height: 800,
    depth: 600,
    depth2: 300,
    pieces: [],
  },
];

const alacenaCabinets: Cabinet[] = [
  {
    id: 'wall-600',
    name: 'Alacena 600mm',
    type: 'wall',
    icon: Archive,
    width: 600,
    height: 600,
    depth: 320,
    pieces: [
      { name: 'Puerta', width: 596, height: 596, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
  {
    id: 'wall-microwave-600',
    name: 'Porta Microondas',
    type: 'wall',
    icon: Microwave,
    width: 600,
    height: 800,
    depth: 400,
    pieces: [],
    defaultComponents: [
      { type: 'opening', height: 400 },
      { type: 'door', height: 400, hinge: 'top' },
    ]
  },
];

const columnaCabinets: Cabinet[] = [
  {
    id: 'tall-600',
    name: 'Columna 600mm',
    type: 'tall',
    icon: Container,
    width: 600,
    height: 2000,
    depth: 580,
    pieces: [
      { name: 'Puerta Superior', width: 596, height: 1246, quantity: 1, material: MELAMINE_MATERIAL },
      { name: 'Puerta Inferior', width: 596, height: 716, quantity: 1, material: MELAMINE_MATERIAL },
    ],
  },
];

const vanitoryCabinets: Cabinet[] = [
    {
      id: 'vanity-600-patas',
      name: 'Vanitory 600mm Patas',
      type: 'base',
      icon: Box,
      width: 600,
      height: 840,
      depth: 460,
      pieces: [], // Will be generated by logic
      defaultComponents: [
        { type: 'drawer', height: 200 },
        { type: 'door', height: 640 },
      ]
    },
];

export const cabinetCategories = [
    { name: "Bajo Mesada", cabinets: bajoMesadaCabinets },
    { name: "Alacenas", cabinets: alacenaCabinets },
    { name: "Columnas", cabinets: columnaCabinets },
    { name: "Vanitory", cabinets: vanitoryCabinets },
];

// Flattened list for compatibility with other parts of the app
export const cabinetData: Cabinet[] = cabinetCategories.flatMap(category => category.cabinets);
